### ISSUE TITLE
SPA issues

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-js#269] opened 2024-08-21 18:33 UTC
Since the update from 4.x to 5.x the ringcentral.js no longer works in a standard spa web page.  If you are going to require buffer, and other items, why don't you pack them using webpack, or provide the appropriate way you would like those references done in a website.       e.isBuffer = Buffer.isBuffer for example is first error when trying use the ringcentral.js in a standard web page.

**Comment by SushilMallRC** [comment] 2024-08-26 09:12
@dougroutledge PR https://github.com/ringcentral/ringcentral-js/pull/270 has been merge for this issue, will update here once release a new version.

**Comment by SushilMallRC** [comment] 2024-08-26 09:33
A new version, 5.0.3, has been released, which includes a fix for this issue. Please update to this version and check if the issue is resolved. Closing this issue for now please feel free to reopen or create a new one. Thank You.

**Closed by SushilMallRC** 2024-08-26 09:33 UTC
